<template>
	<div id="header" height="auto" class="header hero-img d-flex justify-center align-center flex-column">
		<div class="hero-shadow"></div>
		<div class="text text-center px-1 d-flex flex-column align-center justify-center">
			<h1 class="white--text text-h3 text-uppercase mb-5">Zapraszamy do naszej ekipy!</h1>
			<p class="white--text text-h5">Trwa rekrutcja!</p>
			<v-btn @click="scrollRecruitment" color="primary">
				<v-icon class="mr-2">mdi-movie-open</v-icon>
				Dołącz do nas!
			</v-btn>
		</div>

		<v-btn class="bounce-top" @click="scroll" text fab>
			<v-icon color="blue" size="40">mdi-arrow-down</v-icon>
		</v-btn>
	</div>
</template>
<script>
export default {
	name: 'HeaderScreen',
	components: {},

	setup() {
		function scroll() {
			const el = document.getElementById('aboutus')
			el.scrollIntoView({ behavior: 'smooth' })
		}
		function scrollRecruitment() {
			const recrut = document.getElementById('recruitment')
			recrut.scrollIntoView({ behavior: 'smooth' })
		}
		return { scroll, scrollRecruitment }
	},
}
</script>
<style lang="scss">
.header {
	scroll-margin: 69px;
}
.hero-img {
	position: relative;
	height: 95vh;
	background-image: url(../assets/img/header.jpg);
	background-size: cover;
	background-position: center;
	background-attachment: fixed;
	z-index: 1;

	.hero-shadow {
		position: absolute;
		height: 100%;
		width: 100%;
		background-color: rgba(0, 0, 0, 0.7);
		z-index: 0;
	}
	.text {
		height: 88%;
		z-index: 2;
	}
}
.bounce-top {
	display: block;
	animation: bounce-top 2s infinite both;
}
/* ----------------------------------------------
* Generated by Animista on 2022-11-18 11:34:9
* Licensed under FreeBSD License.
* See http://animista.net/license for more info. 
* w: http://animista.net, t: @cssanimista
* ---------------------------------------------- */

/**
* ----------------------------------------
* animation bounce-top
* ----------------------------------------
*/

@keyframes bounce-top {
	0% {
		-webkit-transform: translateY(-45px);
		transform: translateY(-45px);
		-webkit-animation-timing-function: ease-in;
		animation-timing-function: ease-in;
		opacity: 1;
	}
	24% {
		opacity: 1;
	}
	40% {
		-webkit-transform: translateY(-24px);
		transform: translateY(-24px);
		-webkit-animation-timing-function: ease-in;
		animation-timing-function: ease-in;
	}
	65% {
		-webkit-transform: translateY(-12px);
		transform: translateY(-12px);
		-webkit-animation-timing-function: ease-in;
		animation-timing-function: ease-in;
	}
	82% {
		-webkit-transform: translateY(-6px);
		transform: translateY(-6px);
		-webkit-animation-timing-function: ease-in;
		animation-timing-function: ease-in;
	}

	25%,
	55%,
	75%,
	87% {
		-webkit-transform: translateY(0px);
		transform: translateY(0px);
		-webkit-animation-timing-function: ease-out;
		animation-timing-function: ease-out;
	}
	100% {
		-webkit-transform: translateY(0px);
		transform: translateY(0px);
		-webkit-animation-timing-function: ease-out;
		animation-timing-function: ease-out;
		opacity: 1;
	}
}
</style>
